import pathlib

BRISC_DATA_PATH = pathlib.Path("brisc2025")

CLASSIFICATION_PATH = BRISC_DATA_PATH / "classification_task"
CLASSIFICATION_TRAIN_PATH = CLASSIFICATION_PATH / "train"
CLASSIFICATION_TEST_PATH = CLASSIFICATION_PATH / "test"

SEGMENTATION_PATH = BRISC_DATA_PATH / "segmentation_task"
SEGMENTATION_TRAIN_PATH = SEGMENTATION_PATH / "train"
SEGMENTATION_TEST_PATH = SEGMENTATION_PATH / "test"

METADATA_FILE = BRISC_DATA_PATH / "manifest.csv"
